# !/bin/bash

function usage() {
    echo "Update native versions in nativescript application script..."
    echo "--help, -h, h, help show the help information."
    echo "--version-to-update, -version-to-update, version-to-update, versionToUpdate can be used with private|public|all values. Specify which version should be updated. Private versions are versionCode and CFBundleVersion."
    echo "--platform, -platform, platform can be used with android|ios|both values. Specify which native version should be updated."
    echo "--cf-bundle-short-version-string, -cf-bundle-short-version-string, cf-bundle-short-version-string, cfbundleshortversionstring is the public ios version. The format is {Number}.{Number}. If not specified it is going to be autogenerated with epoch time."
    echo "--cf-bundle-version, -cf-bundle-version, cf-bundle-version, cfbundleversion is the private ios version. The format is {Number}.{Number}.{Number}. If not specified it is going to be autogenerated with epoch time."
    echo "--version-name, -version-name, version-name, versionname is the public android version. The format is {Number}.{Number}. If not specified it is going to be autogenerated with epoch time."
    echo "--version-code, -version-code, version-code, versioncode is the private android version. The format is {Number}. If not specified it is going to be autogenerated with epoch time."
    echo "--path-to-n-project, -path-to-n-project, path-to-n-project, pathtonproject is used for specifying path to the nativescript project. If not specified current location is assumed as path for the projec."
}

function generateVersion() {
    # get epoch time 
    local version=`date +%s`
    echo $version
}

function getPathToFiles() {
    path=""
    if [ "$2" == "" ]; then
        path=".""$1"
    else
        path="$2""$1"
    fi
    echo $path
}

function updateAndroidversionCode() {
    echo "update android version code"
    androidManifestFile=$(getPathToFiles "/app/App_Resources/Android/src/main/AndroidManifest.xml" "$2") 

    value=`cat ${androidManifestFile}`
    androidRegex="versionCode\=\"([0-9]+)\""
    if [[ $value =~ $androidRegex ]]; then
    androidVersionCode="${BASH_REMATCH[1]}"
    fi
    androidOldValue="versionCode=\"${androidVersionCode}\""
    androidNewValue="versionCode=\"${1}\""

    echo "new version code: ${androidNewValue}"
    `sed -i "" "s/${androidOldValue}/${androidNewValue}/g" ${androidManifestFile}`
}

function updateVersionName() {
    echo "update android version name"
    androidManifestFile=$(getPathToFiles "/app/App_Resources/Android/src/main/AndroidManifest.xml" "$2") 
    value=`cat ${androidManifestFile}`
    androidRegex="versionName\=\"([0-9]+).([0-9]+)\""
    if [[ $value =~ $androidRegex ]]; then
    major="${BASH_REMATCH[1]}"
    minor="${BASH_REMATCH[2]}"
    fi
    androidOldValue="versionName=\"${major}.${minor}\""
    androidNewValue=""
    regexWithTwoVersions="([0-9]+)\.([0-9]+)"
    if [[ ${1} =~ $regexWithTwoVersions ]]; then
        major="${BASH_REMATCH[1]}"
        minor="${BASH_REMATCH[2]}"
        androidNewValue="versionName=\"${major}.${minor}\""
    else
        androidNewValue="versionName=\"${major}.${1}\""
    fi
    echo "new version name: ${androidNewValue}"
    `sed -i "" "s/${androidOldValue}/${androidNewValue}/g" ${androidManifestFile}`
}

function updateIOSCFBundleVersion() {
    echo "update ios CFBundleVersion"
    iosInforPlistFile=$(getPathToFiles "/app/App_Resources/iOS/Info.plist" "$2") 
    inforPlistValue=`cat ${iosInforPlistFile}`
    major=0
    minor=0
    build=0
    iosRegex="<key>CFBundleVersion<\/key>(.+)<string>([0-9]+).([0-9]+).([0-9]+)"
    if [[ $inforPlistValue =~ $iosRegex ]]; then
    major="${BASH_REMATCH[2]}"
    minor="${BASH_REMATCH[3]}"
    build="${BASH_REMATCH[4]}"
    fi
    iosOldValue="<string>${major}.${minor}.${build}</string>"
    iosNewValue=""
    regexWithFullVersion="([0-9]+)\.([0-9]+)\.([0-9]+)"
    regexWithTwoVersions="([0-9]+)\.([0-9]+)"
    if [[ ${1} =~ $regexWithTwoVersions ]]; then
        minor="${BASH_REMATCH[1]}"
        build="${BASH_REMATCH[2]}"
        iosNewValue="<string>${major}.${minor}.${build}</string>"
        if [[ ${1} =~ $regexWithFullVersion ]]; then
            major="${BASH_REMATCH[1]}"
            minor="${BASH_REMATCH[2]}"
            build="${BASH_REMATCH[3]}"
            iosNewValue="<string>${major}.${minor}.${build}</string>"
        fi
    else
        iosNewValue="<string>${major}.${minor}.${1}</string>"
    fi
    echo "new version: ${iosNewValue}"
    `sed -i "" "s|${iosOldValue}|${iosNewValue}|g" ${iosInforPlistFile}`
}

function updateIOSCFBundleShortVersionString() {
    echo "update ios CFBundleShortVersionString"
    iosInforPlistFile=$(getPathToFiles "/app/App_Resources/iOS/Info.plist" "$2") 
    inforPlistValue=`cat ${iosInforPlistFile}`
    major=0
    minor=0
    build=0
    iosRegex="<key>CFBundleShortVersionString<\/key>(.+)<string>([0-9]+).([0-9]+)</string>"
    if [[ $inforPlistValue =~ $iosRegex ]]; then
    major="${BASH_REMATCH[2]}"
    minor="${BASH_REMATCH[3]}"
    fi
    iosOldValue="<string>${major}.${minor}</string>"
    iosNewValue=""
    regexWithTwoVersions="([0-9]+)\.([0-9]+)"
    if [[ ${1} =~ $regexWithTwoVersions ]]; then
        major="${BASH_REMATCH[1]}"
        minor="${BASH_REMATCH[2]}"
        iosNewValue="<string>${major}.${minor}</string>"
    else
        iosNewValue="<string>${major}.${1}</string>"
    fi
    echo "new version: ${iosNewValue}"
    `sed -i "" "s|${iosOldValue}|${iosNewValue}|g" ${iosInforPlistFile}`
}

# intialize variables
args=("$@")
versionsToUpdate=""
platform=""
CFBundleShortVersionString=""
CFBundleVersion=""
versionName=""
versionCode=""
pathToNProject=""

# process arguments
for (( i=0; i<=$#-1; i++ ))
  do 
    argumentLowerCase="$(tr [A-Z] [a-z] <<< "${args[i]}")"
    argument="${argumentLowerCase//-/}"
    case "$argument" in
        "help"|"h")
            usage
            break
			;;
		"versiontoupdate")
            versionsToUpdate="$(tr [A-Z] [a-z] <<< "${args[i+1]}")"
			;;
		"platform")
            platform="$(tr [A-Z] [a-z] <<< "${args[i+1]}")"
			;;
		"cfbundleshortversionstring")
            CFBundleShortVersionString=${args[i+1]}
			;;
		"cfbundleversion")
            CFBundleVersion=${args[i+1]}
			;;
		"versionname")
            versionName=${args[i+1]}
			;;
		"versioncode")
            versionCode=${args[i+1]}
			;;
		"pathtonproject")
            pathToNProject=${args[i+1]}
			;;
    esac
 done

# echo $versionsToUpdate
# echo $platform
# echo $CFBundleShortVersionString
# echo $CFBundleVersion
# echo $versionName
# echo $versionCode
# echo $pathToNProject

case "$platform" in
		"android")
            if [ "$versionsToUpdate" == 'private' ] || [ "$versionsToUpdate" == 'all' ] || [ "$versionsToUpdate" == '' ]
            then
                if [ "$versionCode" == "" ]; then
                    versionCode=$(generateVersion) 
                fi 
                updateAndroidversionCode $versionCode $pathToNProject
            fi
            if [ "$versionsToUpdate" == 'public' ] || [ "$versionsToUpdate" == 'all' ] 
            then
                if [ "$versionName" == "" ]; then
                    versionName=$(generateVersion)
                fi 
                updateVersionName $versionName $pathToNProject
            fi
			;;
		"ios")

            if [ "$versionsToUpdate" == 'private' ] || [ "$versionsToUpdate" == 'all' ] || [ "$versionsToUpdate" == '' ]
            then
                if [ "$CFBundleVersion" == "" ]; then
                    CFBundleVersion=$(generateVersion) 
                fi 
                updateIOSCFBundleVersion $CFBundleVersion $pathToNProject
            fi
            if [ "$versionsToUpdate" == 'public' ] || [ "$versionsToUpdate" == 'all' ] 
            then
                if [ "$CFBundleShortVersionString" == "" ]; then
                    CFBundleShortVersionString=$(generateVersion)
                fi 
                updateIOSCFBundleShortVersionString $CFBundleShortVersionString $pathToNProject
            fi
			;;
		"both")
            if [ "$versionsToUpdate" == 'private' ] || [ "$versionsToUpdate" == 'all' ] || [ "$versionsToUpdate" == '' ]
            then
                if [ "$versionCode" == "" ]; then
                    versionCode="$(generateVersion)"
                fi 
                if [ "$CFBundleVersion" == "" ]; then
                    CFBundleVersion=$(generateVersion) 
                fi 
                updateAndroidversionCode $versionCode $pathToNProject
                updateIOSCFBundleVersion $CFBundleVersion $pathToNProject
            fi
            if [ "$versionsToUpdate" == 'public' ] || [ "$versionsToUpdate" == 'all' ] 
            then
                if [ "$versionName" == "" ]; then
                    versionName=$(generateVersion)
                fi 
                if [ "$CFBundleShortVersionString" == "" ]; then
                    CFBundleShortVersionString=$(generateVersion)
                fi
                updateVersionName $versionName $pathToNProject
                updateIOSCFBundleShortVersionString $CFBundleShortVersionString $pathToNProject
            fi
			;;
	esac


